name: NodeGoat Vorpal Security Analysis

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allow manual triggering

jobs:
  vorpal-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Get changed files for focused scanning
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ','
          files: |
            **/*.js
            **/*.json
        
      # Run Vorpal on changed files
      - name: Vorpal Security Scan - Changed Files
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: checkmarx/vorpal-reviewdog-github-action@v1.0.0
        with:
          source_path: "${{ steps.changed-files.outputs.all_changed_files }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          fail_on_error: false
          filter_mode: file
          
      # Full scan on main vulnerable directories
      - name: Vorpal Security Scan - Full Scan
        if: github.event_name == 'push'
        uses: checkmarx/vorpal-reviewdog-github-action@v1.0.0
        with:
          source_path: "app/routes,app/data,app/views,test"
          folders_to_ignore: "node_modules,coverage,logs"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_on_error: true # Fail build on security issues
          reviewdog_flags: "--level-map=high:error,medium:warning,low:info"
