name: Vorpal SAST Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vorpal-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Vorpal Scan
        uses: checkmarx/vorpal-reviewdog-github-action@v1.2.0
        with:
          source_path: app/routes
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          filter_mode: file
